version: '3.8'

services:
  db:
    image: postgres:15
    container_name: odoo18-db
    restart: always
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - odoo-network

  odoo:
    image: satheeshkumar221297/odoo18-custom:latest
    container_name: odoo18
    depends_on:
      - db
    restart: always
    ports:
      - "8069:8069"
    volumes:
      - /opt/odoo18/config:/etc/odoo
      - /opt/odoo18/data:/var/lib/odoo      # ✅ Persistent filestore
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    networks:
      - odoo-network

networks:
  odoo-network:

volumes:
  db_data:
